### ISSUE TITLE
Mistake in scoping example

### ISSUE THREAD

**Issue by Mahesha999** [less/less-docs#167]
Found a mistake in variable scoping / evaluation example at there:
http://lesscss.org/features/#variables-feature-lazy-loading 

The Given LESS:

``` less
@var: 0;
.class1 {
  @var: 1;
  .class {
    @var: 2;
    three: @var;
    @var: 3;
  }
  one: @var;
}
```

The Given Output:

```
.class1 .class {
  three: 3;
}
.class {  //this should be .class1
  one: 1;
}
```
