### ISSUE TITLE
Confusing example for using variables to define variable value

### ISSUE THREAD

**Issue by Mahesha999** [less/less-docs#171]
The example here : http://lesscss.org/features/#variables-feature-variable-names 
is confusing:

```less
@fnord:  "I am fnord.";
@var:    "fnord";
content: @@var;   //this should not float in air I guess, should be enclosed in some CSS rule
```
I found this a bit confusing since am comparatively new to LESS, and initially I thought ``content`` is some another LESS construct that I am unaware of.
Something like this might bring more clearity:

```less
@color1 : #ffd800;
@color2 : "color1";
@color3 : @@color2;

.color3demo
{
    background-color : @color3;  //evaluates to #ffd800
}
```
