### ISSUE TITLE
Question: "Passing ruleset to mixin" confusion

### ISSUE THREAD

**Issue by am11** [less/less-docs#191]
Confused by [this piece of documentation](http://lesscss.org/features/#detached-rulesets-feature).

What is the difference between:

``` scss
@my-ruleset: {
    .my-selector {
      @media tv {
        background-color: black;
      }
    }
};
@media (orientation:portrait) {
    @my-ruleset();
}
```

and

``` scss
@my-ruleset: {
    @media tv {
      .my-selector {
        background-color: black;
      }
    }
};
@media (orientation:portrait) {
    @my-ruleset();
}
```

The compiled output is same:

``` scss
@media (orientation: portrait) and tv {
  .my-selector {
    background-color: black;
  }
}
```

 But what if we need:

``` scss
@media (orientation: portrait) {
  .my-selector {
    @media tv {
      background-color: black;
    }
  }
}
```

Is there a way to pass rule-set while retaining the sequence of nested blocks?
