### ISSUE TITLE
Better explain import by reference with html tag based rules.

### ISSUE THREAD

**Issue by AoDev** [less/less-docs#205]
Hello, 

A simple observation. When I use:

```
@import (reference) "docs.less";
```

if docs.less contains tag rules like this:

``` css
div {
    background-color: #000;
}

.black {
    background-color: #000;
}
```

The first rule will be outputted. No problem here. But it's not mentioned in the docs.

I actually use this feature in a real use case. For example, I import twitter bootstrap as a "mixin" library. I import the forms related less file by reference and then pick only what I need. (but it still outputs their form related tag rules, which is needed)

I want to make sure that it's an expected behaviour, clarify the docs and that it won't change in the future. (well it would break my stuff ;)
