### ISSUE TITLE
How to keep duplicate properties in compiled CSS file?

### ISSUE THREAD

**Issue by yulanggong** [less/less-docs#270]
LESS code

``` less
.foo {
  background-size: 200px; //for old browsers
  background-size: cover;
}
```

CSS expected

``` css
.foo {
  background-size: 200px; 
  background-size: cover;
}
```
