### ISSUE TITLE
sourceMap use

### ISSUE THREAD

**Issue by DarkPark** [less/less-docs#282]
It's not clear how to generate source maps.
There is a single paragraph about it in http://lesscss.org/usage/#programmatic-usage.
Without even a simple example it's impossible to make it work easily.
Can you please provide an example?

**Comment by bassjobsen** [comment]
Hi @DarkPark, on the first sight the docs look pretty straight forward. But some points possible need more explanation. 
If you already have some non working code, stackoverflow will maybe a better place to ask your questions.

First of all you should notice the difference between the less.js in browser compiler and the node compiler. When your are using the in browser compiler you can not use sourcemaps at all, due to https://github.com/less/less.js/issues/1541

The docs describe two ways to call less.render:

1) `less.render(lessInput,optionObject,function(error,output){}` which should be used when `less = require('less');` after running `npm install less`. The second parameter (`output`) of the anymous function in the preceding will always return a string. If you have set the sourcemap option, your sourcemap will be append to the `output` string.

An example:

```css
less = require('less');
less.render('@c: red; p{c: @c;}',{sourceMap:{}},function(error,output)
{
console.log(typeof output);
console.log(output);
});
```
outputs:

```
string
p {
  c: #ff0000;
}
/*# sourceMappingURL=data:application/json,%7B%22version%22%3A3%2C%22sources%22%3A%5B%22input%22%5D%2C%22names%22%3A%5B%5D%2C%22mappings%22%3A%22AAAU%3BEAAC%2CUAAA%22%7D */
```

2) The `less` object is a promise object. This happens when you use the in browsers less.js or less-node (`less = require(less/lib/less-node)`). With the promise object you can use: less.render(lessInput).then(function(output) {});`

In the above `output` is a object; `output.css` holds the compiled code and `output.css` the sourcemap code when sourcemaps are enabled:

An example:

```css
less = require('/usr/local/lib/node_modules/less/lib/less-node');

less.render('@c: red; p{c: @c;}',{sourceMap:{}})
    .then(function(output) {
    console.log('output.css: ' + output.css + "\n");
    console.log('output.map: ' + output.map + "\n");
});
```

outputs:

```css
output.css: p {
  c: red;
}
output.map: {"version":3,"sources":["input"],"names":[],"mappings":"AAAS;EAAE,MAAA"}

```
Without the sourcemaps enabled, as explain above, you can run the same code in your browser:

```html
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script>
less.render('@c: red; p{c: @c;}',{})
    .then(function(output) {
    console.log('output.css: ' + output.css + "\n");
    console.log('output.map: ' + output.map + "\n");//undefined now
});
</script>
```	
The docs also tell you that you can set the sourcemap option object in the .then(function(output,{sourceMap:{}}) function. I believe this is wrong. Options should be set in the render call. So you should use the following code:

```javascript
less.render(lessInput,{sourceMap:{}})
    .then(function(output) {
        // output.css = string of css
        // output.map = string of sourcemap
}
```																														

Finally when you are looking for a example of the use of less-node (the promise method) you can take a look at [the source of the command line compiler](https://raw.githubusercontent.com/less/less.js/master/bin/lessc).
