### ISSUE TITLE
Wrong calc compilation

### ISSUE THREAD

**Issue by tompazourek** [less/less-docs#342]
When I compile this code (note that it is valid and working CSS):

```CSS
ul.timeline > li > .timeline-panel {
  width: calc(100% - 90px);
  width: -moz-calc(100% - 90px);
  width: -webkit-calc(100% - 90px);
}
```

I get this output:

```CSS
ul.timeline > li > .timeline-panel {
  width: calc(10%);
  width: -moz-calc(10%);
  width: -webkit-calc(10%);
}
```
