### ISSUE TITLE
@@variable parsing

### ISSUE THREAD

**Issue by Enelar** [less/less-docs#350]
I did it with properties:
```css
.cutting-edge-mixin(@name, @code) {
  @{name}:@code;
  -o-@{name}:@code;
  -ms-@{name}:@code;
  -moz-@{name}:@code;
  -webkit-@{name}:@code;
}
```
Now im able to reference animation with:
```css
.animation-mixin(@code) {
  .cutting-edge-mixin(animation, @code);
}
a {
  .animation-mixin(aura-blink 4s linear infinite);
}
```

But i still unable to create keyframes for it.

```css
.cutting-edge-at-mixin(@suffix, @code) {
  @@suffix {@code();}
  @-o-@suffix {@code();}
  @-ms-@suffix {@code();}
  @-moz-@suffix {@code();}
  @-webkit-@suffix {@code();}
}
```
It failing because of `@@` construction.
I tried already `~"@@{suffix}"` `~"@"@suffix` and other variations.

When it become possible, i will get power on that magic:
```css
.keyframes-mixin(@name, @code) {
  .cutting-edge-at(~"keyframes @{name}", @code);
}

.keyframes-mixin(aura-blink, {
  0% { background-color: rgba(0, 107, 171, 0); }
  50% { background-color: rgba(0, 107, 171, 0.2); }
  100% { background-color: rgba(0, 107, 171, 0); }
});
```
