### ISSUE TITLE
not selector handle issue

### ISSUE THREAD

**Issue by LiaoSept** [less/less-docs#385]
less code:
```less
.element:not(.not-element) {
    &.target:first-child {
         display: block;
    }
}
```
build results:
```css
.element:not(.not-element).target:first-child {
     display: block;
}
```
i want:
```css
.element.target:not(.not-element):first-child {
     display: block;
}
```
