### ISSUE TITLE
LESS Reference Manual— I think there are three mistakes need correction

### ISSUE THREAD

**Issue by golegen** [less/less-docs#404]
## Please visit [Less manual website](http://lesscss.org/features/#mixins-parametric-feature)
I have run the test code such as the following，
I have some questions and would like to share.

the page—— # Language Features

1.Click the left column：Passing Rulesets to Mixins
Look at right column code：
I think it should be after the Number 1200 , need to add "px"
Reads as follows

> Here the desktop-and-old-ie mixin defines the media query and root class so that you can use a mixin to wrap a piece of code. This will output
```less
.desktop-and-old-ie(@rules) {
      @media screen and (min-width: 1200) { @rules(); }
      html.lt-ie9 &                       { @rules(); }
}
header {
      background-color: blue;
      .desktop-and-old-ie({
            background-color: red;
      });
}
```
> 

2.Click the left column：Passing Rulesets to Mixins
Look at right column code： 
I think it should be in front of the word "detached-ruleset" to add a symbol "@" .
Reads as follows

>Private variables:
```less
detached-ruleset: { 
    @color:blue; // this variable is private
};
.caller {
    color: @color; // syntax error
}
```
> 

3.Click the left column：Scoping
Look at right column code： 
I run the following code，but the result is “value” not the "global".
Reads as follows

> 
Variable and mixins accessible form definition win over those available in the caller:
```less
@variable: global;
@detached-ruleset: {
  // will use global variable, because it is accessible
  // from detached-ruleset definition
  variable: @variable; 
};
selector {
  @detached-ruleset();
  @variable: value; // variable defined in caller - will be ignored
}
```
 compiles into:
```less
selector {
  variable: global;
//  I run the following code，but the result is “value” not the "global".
}
```
>
