### ISSUE TITLE
Detached ruleset scopes are affected when I refer to the code in the manual for testing

### ISSUE THREAD

**Issue by golegen** [less/less-docs#405]
When I refer to the code in the manual for testing,I found the detached ruleset scopes affected.
( use webstorm and less 2.6.1)
View code,Please visit [Less manual website](http://lesscss.org/features/#detached-rulesets-feature-scoping)

Reads as follows
> 
Variable and mixins accessible form definition win over those available in the caller:
```less
@variable: global;
@detached-ruleset: {
  // will use global variable, because it is accessible
  // from detached-ruleset definition
  variable: @variable; 
};
selector {
  @detached-ruleset();
  @variable: value; // variable defined in caller - will be ignored
}
```
compiles into:
```css
selector {
  variable: global;
}
```
> 

### If you add additional code in front of manual reference code,for example:
```less
//additional code
@testvalue: 2px;
#test {
  width: @testvalue;
}
//manual reference code
@variable: global;
@detached-ruleset: {
  // will use global variable, because it is accessible
  // from detached-ruleset definition
  variable: @variable; 
};
selector {
  @detached-ruleset();
  @variable: value; // variable defined in caller - will be ignored
}
```
compiles into:
```css
#test {
  width: 2px;
}
selector {
  variable: value;
}
```
The value of `variable`: `global` becomes `value`;
I can't explain，so I can not to mislead others.
I was a rookie, and I'm learning ,but I still wanted to share it.
