### ISSUE TITLE
Cannot import the same file at one time

### ISSUE THREAD

**Issue by chenyuncai** [less/less-docs#407]
Hello, There is a problem that i found.

Here are some less files below:

a,b,c,d

a import b
a import c

b import d
c import d

I can only import the d file in b's place if the b is before c in a file;

I want use the common styles with a different container so that I can location the exact elements.
Thanks ^U^

**Comment by seven-phases-max** [comment]
Note this issue tracker is for the Less documentation development. For the Less language and compiler issues use 

Either way, what you face is an intended behaviour: http://lesscss.org/features/#import-options.

**Comment by seven-phases-max** [comment]
Closing as expected behaviour (and wrong repo).

**Comment by golegen** [comment]
@chenyuncai , 您好，您发给我的邮件我看过了，您在邮件中说的也很明白。
现在，我将您的想法，大概描述一下，以方便其他人了解您的意图。

> 
Filename : a.less
```less
#a {
    @import "b.less";
    @import "c.less";
}
```
Filename : b.less
```less
#b {
    @import "d.less";
}
```
Filename : c.less
```less
#c {
    @import "d.less";
}
```
Filename : d.less
```less
#d {
    color: red;
}
```
> 

现在，您的预期结果是
```css
#a #b #d {
    color: red;
}

#a #c #d {
    color: red;
}
```
但是，实际只有一个结果：
```css
.a #b #d {
    color: red;
}
```

### 下面是解决方案(Solution)
现在，您把 A.file 的内容修改为：
```less
#a {
  @import (multiple) "b.less";
  @import (multiple) "c.less";
}
```
编译结果为
```css
#a #c #d {
    color: red;
}
#a #b #d {
    color: red;
}
```

### 您还可以测试几个案例，以便了解更多：
### test 1
a.less
```less
/*
#a {
    @import "b.less";
    @import "c.less";
}
*/
#a {
    @import "c.less";
    @import "b.less";
}
```
交换这两个@ import 的位置，可能跟优先级有关，编译结果为：
```css
/*
#a #b #d {
    color: red;
}
*/
#a #c #d {
    color: red;
}
```

### test 2
a.less
```less
#a {
    @import "b.less";
    @import "c.less";
}
#k {
    @import "c.less";
    @import "b.less";
}
/*
#k {
    @import "c.less";
    @import "b.less";
}
#a {
    @import "b.less";
    @import "c.less";
}
*/
```
编译结果：
```css
#a #b #d {
    color: red;
}
/*
#k #b #d {
    color: red;
}
*/
```

### test 3
a.less
```less
#a {
    @import (multiple) "c.less";
    @import (multiple) "b.less";
}

.k {
    @import "b.less";
    @import "c.less";
}
```
编译结果：
```css
#a #c #d {
  color: red;
}
#a #b #d {
  color: red;
}
// K not compiled
// K 未编译
```

### test 4
a.less
```less
#a {
    @import (multiple) "c.less";
    @import (multiple) "b.less";
}

.k {
    @import (multiple) "b.less";
    @import (multiple) "c.less";
}
```
编译结果：
```css
#a #c #d {
    color: red;
}
#a #b #d {
    color: red;
}
.k #b #d {
    color: red;
}
.k #c #d {
    color: red;
}
```
