### ISSUE TITLE
problem with setting my body background color

### ISSUE THREAD

**Issue by GaneshKandu** [less/less-docs#412]
Hi 
I am Trying to set My Background #FFF of body tag
- index.html
```html
<!DOCTYPE html>
<html>
<head>
<title>title</title>
<script type="text/javascript"  src="js\less.min.js" ></script>
<link rel="stylesheet/less" type="text/css" href="less\lesscss.less" />
<link rel="stylesheet" type="text/css" href="css\style.css">
</head>
<body>
<div id="cont">
</div>
</body>
</html>
```
- 2 style.css
```css
body {
        position: absolute;
        margin: 0px;
        padding: 0px;
        top: 0px;
        left: 0px;
        right: 0px;
        bottom: 0px;
        display:block;
}
#JDBMngr_cont {
	background-color: rgb(0, 0, 0);
        width: 100%;
        height: 100%;
}
```
- 3 lesscss.less
```css
body {
    display:block;
}
```
i am trying to set background black
but less.min.js is setting it to
```css
body {
    display: none !important;
}
```
default i am tried with less also to set 
```css
body {
    display:block;
}
```
but its not working please suggest any solution :+1:
