### ISSUE TITLE
Issue with em length unit (giving different results)

### ISSUE THREAD

**Issue by carlosmiguelsns** [less/less-docs#448]
Hi guys, think I'm facing some issue with compiling values using _em_ length unit.

When I use 1.2em on the @font-size-base var, the next instruction **@line-height-computed:  floor((@font-size-base * @line-height-base))** returns a different results then when I'm using the 1.2 without _em_.
e.g.:
```less
@font-size-base:1.2em ->  .input-group-lg input[type="month"]{line-height:25em}
@font-size-base:1.2:      -> .input-group-lg input[type="month"]{line-height:25px}
```
Thanks
