### ISSUE TITLE
:extend(.class all) not working properly

### ISSUE THREAD

**Issue by zFunx** [less/less-docs#463]
I'm learning LESS, I have tested the following code at http://less2css.org/
````css
nav ul:extend(.inline all) {
  
  background: blue;
}
.bg.inline{
	background:red
}
````
And the output is : 
````css
nav ul {
  background: blue;
}
.bg.inline,
.bgnav ul {
  background: red;
}
````
.bgnav is wrong
