### ISSUE TITLE
how i can divider image size in version 1.5?

### ISSUE THREAD

**Issue by golestan-melika** [less/less-docs#502]
hello
i have a problem , my teacher says we must have image-width and image-height in less 1.5 version , but we just have image-size in it. 
how i can solve it?

**Comment by seven-phases-max** [comment]
`image-size` returns a list of values so you can get each value individually with [`extract`](http://lesscss.org/functions/#list-functions-extract). E.g.:
```less
foo {
    @size: image-size("x.png");
    width:  extract(@size, 1);
    height: extract(@size, 2);
}
```
