### ISSUE TITLE
GUID NEEDED: comment before child, shown in parent scope

### ISSUE THREAD

**Issue by noommii** [less/less-docs#504]
comment before child id(#) shown in parent selector(header) after compiling.

LESS:
`header {
    box-shadow: 0px 3px 10px -5px rgb(211, 212, 212);
    background-color: rgb(255, 255, 255);
    /* search button */
    #search-btn {
        text-align: center;
        .query(@middle, {
            text-align: left;
        });
    }
}`

CSS:
`header {
  box-shadow: 0px 3px 10px -5px #d3d4d4;
  background-color: #ffffff;
  /* search button */
}
header #search-btn {
  text-align: center;
}`

**Comment by seven-phases-max** [comment]
There's no way the compiler can guess you want such comment to belong to `#search-btn`.
Basically the code is nothing but:
```less
header { 
    ...
    background-color: rgb(255, 255, 255); 
    /* search button */
    ...
}
```
So the result is perfectly expected (See also #1302, #1879 and similar threads).
