### ISSUE TITLE
Mismatch between Expected and Actual Output in Official Documentation Example

### ISSUE THREAD

**Issue by xiaoyan13** [less/less-docs#618]
**[Here](https://lesscss.org/features/#scope-feature-tips-tricks)**

In this code:
```less
.some-module {
  @height: 200px;
  @width: 200px;
  text-align: left;
  line-height: @height; // 200px

  & {
    // Override original values
    @height: 100px;
    @width: auto;

    .some-module__element {
      height: @height; // 100px
      width: @width; // 200px --- not 200px, but "auto". 
    }
    // ...
  }
  // ...
}
```

There is a problem with the annotation, width of ".some-module__element" is "auto", which overrides original value “200px".
